### ISSUE TITLE
Filtering returns nothing on first search Chrome 53/Windows 10

### ISSUE THREAD

**Issue by seanwash** [seanwash/dnc-topic-search#9]
From loken:

> Odd bug in your new side project, type something into search without hitting enter or anything and click someone else in the body so the input loses focus
> 
> http://d.pr/i/yJxP
> 
> Yeah it's like first page load it always happens, then after clearing the field so it's back to the full list and trying again mostly doesn't work but sometimes does...real weird

**Comment by lokenx** [comment]
Did some digging during some conference down time! It seems that your `filterEpisodes` action isn't getting fired when you click somewhere to lose focus in the search box. The `updateSearchFilter` action does fire however and get updated in Veux. Why that clears all the episodes I'm not entirely sure. You seem to be calling the `updateSearchFilter` only on submit of the form so that doesn't explain why when you clear the input the list re-populates.

However, I haven't used Veux yet so I'm not sure what changes to make exactly (I've done similar filtering but without Veux).

**Comment by seanwash** [comment]
@lokenx thanks for the clarification! I'll check into it some more

**Comment by seanwash** [comment]
I noticed this happening on iOS as well. When you enter a search and click done instead of return on the keyboard the entries disappear but the search filter doesn't happen.

**Comment by lokenx** [comment]
Well you are only dispatching the `filterEpisodes` action on form submit, so when you click outside the form field it doesn't get fired so it won't filter anything.

The state does get updated however...which means your `showEpisodes` computed data uses the `filteredEpisodes` variable (because `this.searchfilters.keywords` is equal to whatever's in the search field) which hasn't been mutated because the action wasn't called!

Hopefully that makes sense 😕 

Edit: which also explains why if you submit the search and get results back and then do the whole clear the field, enter a query, and then click out you won't get a blank list, you'll get the last filtered list that was created on previous query.

I break things, a lot...sorry!

**Comment by seanwash** [comment]
Yeah that makes perfect sense.

Also, no worries!
